### ISSUE TITLE
I'd love to help

### ISSUE THREAD

**Issue by EllaKaye** [ismayc/tamedata#2]
Hello,

I'm keen to get involved with this. I'm in the process of building a data package for my PhD, so know a bit about how to put this kind of thing together. I don't have any datasets in mind, but I'll look through [https://github.com/caesar0301/awesome-public-datasets](https://github.com/caesar0301/awesome-public-datasets) have a think about it (unfortunately the data I'm using for my PhD isn't available for public use). 

Let me know what you think would be most useful at this stage.

**Comment by ismayc** [comment]
Hi Ella.  Sorry for the delay in getting back to you on this.  I will let you know when I get a Google Sheet set up.
